# Generated by Django 3.0.6 on 2020-05-24 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('categoryID', models.AutoField(primary_key=True, serialize=False)),
                ('categoryName', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='gstSlab',
            fields=[
                ('slabId', models.AutoField(primary_key=True, serialize=False)),
                ('slabName', models.CharField(max_length=10)),
                ('slabPercentage', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='item',
            fields=[
                ('itemId', models.AutoField(primary_key=True, serialize=False)),
                ('itemName', models.CharField(max_length=10)),
                ('itemCostinINR', models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ('categoryId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billingWebApp.category')),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('orderId', models.AutoField(primary_key=True, serialize=False)),
                ('orderMode', models.CharField(max_length=10)),
                ('orderSource', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('age', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('paymentId', models.AutoField(primary_key=True, serialize=False)),
                ('totalSubCost', models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ('totalGST', models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ('totalCost', models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ('modeofPayment', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billingWebApp.order')),
            ],
        ),
        migrations.CreateModel(
            name='orderItem',
            fields=[
                ('ordersItemId', models.AutoField(primary_key=True, serialize=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billingWebApp.item')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billingWebApp.order')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billingWebApp.user'),
        ),
        migrations.AddField(
            model_name='category',
            name='gstSlab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billingWebApp.gstSlab'),
        ),
    ]
