# Generated by Django 3.0.6 on 2020-05-24 14:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('billingWebApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='orderDate',
            field=models.CharField(default=datetime.datetime(2020, 5, 24, 14, 3, 34, 639036, tzinfo=utc), max_length=20),
        ),
    ]
