# Generated by Django 3.0.6 on 2020-05-28 01:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('billingWebApp', '0002_order_orderdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='categoryId',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='orderMode',
            new_name='paymentMode',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='item',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='order',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='itemId',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='orderId',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payment',
            name='orderId',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payment',
            name='totalDue',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payment',
            name='totalPaid',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='gstslab',
            name='slabPercentage',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='item',
            name='itemName',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderDate',
            field=models.CharField(default=datetime.datetime(2020, 5, 28, 1, 1, 0, 81809, tzinfo=utc), max_length=20),
        ),
    ]
