# Generated by Django 3.0.6 on 2020-05-24 16:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('billingWebApp', '0003_auto_20200524_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderDate',
            field=models.CharField(default=datetime.datetime(2020, 5, 24, 16, 29, 20, 880113, tzinfo=utc), max_length=20),
        ),
    ]
