# Generated by Django 3.0.6 on 2020-05-27 16:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('billingWebApp', '0009_auto_20200527_2137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='orderDate',
        ),
        migrations.AlterField(
            model_name='order',
            name='orderDate',
            field=models.CharField(default=datetime.datetime(2020, 5, 27, 16, 20, 21, 821243, tzinfo=utc), max_length=20),
        ),
    ]
