# Generated by Django 3.0.6 on 2020-05-27 22:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('billingWebApp', '0013_auto_20200527_2202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='orderMode',
            new_name='paymentMode',
        ),
        migrations.AlterField(
            model_name='order',
            name='orderDate',
            field=models.CharField(default=datetime.datetime(2020, 5, 27, 22, 1, 19, 12661, tzinfo=utc), max_length=20),
        ),
    ]
