# Generated by Django 3.0.6 on 2020-05-27 22:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('billingWebApp', '0014_auto_20200528_0331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='order',
        ),
        migrations.AddField(
            model_name='payment',
            name='orderId',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderDate',
            field=models.CharField(default=datetime.datetime(2020, 5, 27, 22, 6, 14, 806102, tzinfo=utc), max_length=20),
        ),
    ]
