# Generated by Django 3.0.6 on 2020-05-27 23:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('billingWebApp', '0016_auto_20200528_0435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderDate',
            field=models.CharField(default=datetime.datetime(2020, 5, 27, 23, 54, 31, 237079, tzinfo=utc), max_length=20),
        ),
    ]
