# Generated by Django 3.0.6 on 2020-05-28 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billingWebApp', '0003_auto_20200528_0631'),
        ('billingWebApp', '0017_auto_20200528_0524'),
    ]

    operations = [
    ]
